version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: pg-entry
    environment:
      POSTGRES_DB: entries
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data